

class RandomGenerator{
	constructor(min, max){ 
		//takes in the minimum and maximum values
		//if they are not defined, it sets the minimum to 1, and the max to 10
		this.min = min;
		this.max = max;
		//makes storage for the random number
		this.randomNumber = this.generate();
	}
	generate(){
		//make a random value between the minimum and maximum values
		return Math.floor(Math.Random()*this.max) +this.min
		//and store the number into the storage from the constructor
	}
	getRange(min=1, max=10){
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		//returns a basic object literal
		return {min: min, max: max}
	}
	getNum(){
		return this.generate();
		//return the random number that was generated by generate()
	}
}